# Generated by Django 5.1.6 on 2025-02-16 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunSQL("CREATE INDEX idx_username ON auth_user (username)"),
    ]
