# Generated by Django 5.1.6 on 2025-02-16 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import evolution.evolution_core.mechanics.phases
import evolution.evolution_core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Epoch",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=evolution.evolution_core.models.short_uuid,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("epoch_number", models.IntegerField(db_index=True, default=1)),
                (
                    "current_phase",
                    models.CharField(
                        db_index=True,
                        default=evolution.evolution_core.mechanics.phases.Phase[
                            "DEVELOPMENT"
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "previous_epoch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evolution_core.epoch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameAction",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=evolution.evolution_core.models.short_uuid,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actions", models.JSONField(default=list)),
                ("action_number", models.IntegerField(db_index=True, default=0)),
                (
                    "epoch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="evolution_core.epoch",
                    ),
                ),
            ],
            options={
                "ordering": ["-action_number"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=evolution.evolution_core.models.short_uuid,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("active_areas", models.JSONField(default=list)),
                ("waiting_areas", models.JSONField(default=list)),
                ("trait_deck", models.JSONField(default=list)),
                ("game_started", models.BooleanField(db_index=True, default=False)),
                ("game_ended", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_epoch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evolution_core.epoch",
                    ),
                ),
                ("actions", models.ManyToManyField(to="evolution_core.gameaction")),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=evolution.evolution_core.models.short_uuid,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.IntegerField(db_index=True, default=0)),
                ("hand", models.JSONField(default=list)),
                ("animals", models.JSONField(default=list)),
                ("seat_position", models.PositiveIntegerField(null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="evolution_core.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["seat_position"],
            },
        ),
        migrations.AddField(
            model_name="gameaction",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="evolution_core.player"
            ),
        ),
        migrations.AddField(
            model_name="epoch",
            name="current_player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="epochs_as_current_player",
                to="evolution_core.player",
            ),
        ),
        migrations.AddField(
            model_name="epoch",
            name="first_player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="epochs_as_first_player",
                to="evolution_core.player",
            ),
        ),
    ]
