# Generated by Django 5.1.4 on 2025-01-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "evolution_core",
            "0002_alter_game_current_epoch",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="player_table",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="trait_deck",
            field=models.JSONField(default=list, null=True),
        ),
    ]
