# Generated by Django 5.1.4 on 2025-01-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evolution_core", "0004_remove_area_is_active_remove_area_special_effects"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="animal_order",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="player",
            name="animals",
            field=models.ManyToManyField(
                related_name="players", to="evolution_core.animal"
            ),
        ),
    ]
