# Generated by Django 5.1.4 on 2025-01-02 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evolution_core", "0005_player_animal_order_player_animals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epoch",
            name="previous_epoch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="evolution_core.epoch",
            ),
        ),
    ]
