# Generated by Django 5.1.4 on 2025-01-02 23:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evolution_core", "0007_game_ended"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="max_epochs",
        ),
    ]
