# Generated by Django 5.1.4 on 2025-01-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evolution_core", "0008_remove_game_max_epochs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="animal",
        ),
        migrations.RemoveField(
            model_name="action",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="action",
            name="action_set",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="epoch",
            name="current_phase",
            field=models.CharField(default="development", max_length=100),
        ),
    ]
