# Generated by Django 5.1.4 on 2025-01-15 00:52

import django.db.models.deletion
import evolution.evolution_core.mechanics.phases
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evolution_core", "0010_epoch_current_player_alter_epoch_first_player"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="epoch",
            name="current_phase",
            field=models.CharField(
                default=evolution.evolution_core.mechanics.phases.Phase["DEVELOPMENT"],
                max_length=100,
            ),
        ),
    ]
