# Generated by Django 5.1.5 on 2025-01-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evolution_core", "0011_game_created_by_alter_epoch_current_phase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="epoch",
        ),
        migrations.AddField(
            model_name="epoch",
            name="epoch_number",
            field=models.IntegerField(default=1),
        ),
    ]
