# Generated by Django 5.1.5 on 2025-01-17 05:03

import uuid

from django.db import migrations, models

import evolution.evolution_core.mechanics.phases


class Migration(migrations.Migration):
    dependencies = [
        ("evolution_core", "0012_remove_game_epoch_epoch_epoch_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="fat_tokens",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="animal",
            name="food_requirement",
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name="animal",
            name="food_tokens",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="animal",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="is_alive",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="shelter",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="area",
            name="current_tokens_food",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="area",
            name="current_tokens_shelter",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="epoch",
            name="current_phase",
            field=models.CharField(
                db_index=True,
                default=evolution.evolution_core.mechanics.phases.Phase["DEVELOPMENT"],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="epoch",
            name="epoch_number",
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name="epoch",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="active_areas",
            field=models.ManyToManyField(
                db_index=True, related_name="active_games", to="evolution_core.area"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="ended",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="game",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(db_index=True, to="evolution_core.player"),
        ),
        migrations.AlterField(
            model_name="game",
            name="started",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="game",
            name="waiting_areas",
            field=models.ManyToManyField(
                db_index=True, related_name="waiting_games", to="evolution_core.area"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="animals",
            field=models.ManyToManyField(
                db_index=True, related_name="players", to="evolution_core.animal"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="score",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
