# Generated by Django 5.1.5 on 2025-01-17 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evolution_core", "0013_alter_action_id_alter_animal_fat_tokens_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["player", "game", "is_alive"],
                name="evolution_c_player__5902b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["created_by", "started", "ended"],
                name="evolution_c_created_f7a92e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["started", "ended"], name="evolution_c_started_bb6916_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["created_at", "started"], name="evolution_c_created_deb3a6_idx"
            ),
        ),
    ]
