# Generated by Django 5.1.5 on 2025-01-19 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evolution_core", "0014_animal_evolution_c_player__5902b7_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="action",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="action",
            name="epoch",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="evolution_core.epoch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="last_action",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="evolution_core.action",
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["game", "epoch", "created_at"],
                name="evolution_c_game_id_27931e_idx",
            ),
        ),
    ]
