name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Load cached Poetry installation
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: poetry-cache-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
        
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        
    - name: Load cached dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-python-${{ hashFiles('poetry.lock') }}
        
    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install --with test
        
    - name: Run tests
      run: |
        poetry run pytest
